include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
    - web/**
    - static/**
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    avoid_print: false
