name: flow_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  equatable: ^2.0.5
  sqflite_common: ^2.5.0+2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.17.2
  lib5: ^0.1.0
  dart_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 992f8062618ef1e78ee92efc7a709eb0d476e1d0
      path: packages/dart_leap
dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.0
  lints: ^3.0.0
  test: ^1.25.0
