name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project: [api, app, tools]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v4
      - name: Get flutter version
        working-directory: ./
        run: |
          FLUTTER_VERSION=$(cat ./FLUTTER_VERSION)
          echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'any'
      - uses: actions/checkout@v4
      - name: Print Dart SDK version
        run: |
          dart --version
          flutter --version
      - name: Install dependencies
        run: |
          flutter pub get
      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: |
          flutter analyze --fatal-infos
      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: flutter test