name: documentation

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd docs
          yarn install
      - name: Check lint
        run: |
          cd docs
          yarn lint
      - name: Test Build
        run: |
          cd docs
          yarn build
