name: Publish to WinGet
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    runs-on: windows-latest
    steps:

      - if: github.event.action == 'released'
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: LinwoodCloud.Flow
          token: ${{ secrets.CI_PAT }}

      - if: github.event.action == 'prereleased'
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: LinwoodCloud.Flow.Nightly
          token: ${{ secrets.CI_PAT }}
